### ISSUE TITLE
How to visualize results?

### ISSUE THREAD

**Issue by mrdrozdov** [hvy/chainer-infogan#2]
Would like to create some samples like you have of the various categorical/continuous variables. Any recommendations?

**Comment by hvy** [comment]
Hi, I suppose you want to cover two scenarios.

1. **Interpolated Samples** Fixed category variables and linearly interpolated continuous variables. Fixed z.
2. **Categorical Samples** Varying categorical variables. Fixed or varying continuous variables and z.

Here is a script https://github.com/hvy/chainer-gan-improvements/blob/master/sample.py that takes samples from a trained generator model (saved as a file) and outputs an image with tiled samples. However, you need to modify the logic for creating the input z vectors to cover the above mentioned scenarios.

One-hot random categorical vectors are quite easy to create.

```python
import numpy as np
n_cat = 10
n_samples = 100

idxs = np.random.randint(n_cat, size=n_samples)
onehot = np.zeros((n_samples, n_cat)).astype(np.float32)
onehot[np.arange(n_samples), idxs] = 1
```

For linear interpolations, create two random ndarrays and use `numpy.linspace` to get element-wise interpolations. Then use `np.concatenate` to create the final input vector z. 

Let me know if I didn't answer your question!

**Comment by mrdrozdov** [comment]
Thanks! Sorry for not responding earlier. Closing now.
