### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ArghyaPal** [hvy/chainer-infogan#3]
Hi, @hvy First of all Thank You very much for providing us this code..!!

I am very new to chainer (even Python). I get the following error while running your code:
`
  File "train.py", line 88
    x_real = xp.zeros((batch_size, *im_shape), dtype=xp.float32)
                                   ^
SyntaxError: invalid syntax
`

I will be very grateful if you help me to fix the code of your good-self.

Thank You

**Comment by hvy** [comment]
Hi and thanks for contacting.

Which version of Python are you using? If you are running a version 2.x (i.e. not 3.x), it could be caused by the unpacking of the variable `im_shape`, which is a tuple. 

For reference 
http://stackoverflow.com/questions/10792970/python-star-unpacking-for-version-2-7
